### PR TITLE
Leetcode 844

### PR DESCRIPTION
**Pull request by Ritwika101**
Leetcode problem no 844 "Backspace String Compare" solved in C++.

### CODE REVIEW

**Comment by Ritwika101** [comment]
I have done 4 pull requests. Could you please verify them?

**Comment by Ritwika101** [comment]
Please merge this

**Comment by Yogeshk4124** [comment]
> I have done 4 pull requests. Could you please verify them?

go to this link : https://hacktoberfest.digitalocean.com/login
and verify your PR. It contain all your information about hacktoberfest

**Comment by Ritwika101** [comment]
Yes, they are verified and now in the 14 days time limit. Thank you!

**Pull request merged**
